# Methods {-}

The methods section is organized based on the Preferred Reporting Items for Systematic Reviews and Meta-Analyses (PRISMA) checklist. While we refer to fMRI “drug” cue-reactivity (including alcohol) throughout the manuscript, behavioral addiction studies focusing on problematic videogame playing or gambling were not excluded as they constitute a small portion of the cue-reactivity literature and involve cue-reactivity paradigms similar to drug cue-reactivity studies.

**Eligibility criteria:** Original studies were selected according to the criteria outlined below.

**Study design and methodology:** We employed a broad perspective in the inclusion of studies, including all types of original research (e.g., basic research, observational studies, and interventional studies). Only peer-reviewed studies were included.

Of interest were original studies that included one or more fMRI-based investigations as a major part of their methodology, whether as an observational or as a treatment tool (e.g. in fMRI neurofeedback). For at least some of the study population, the fMRI investigation had to include a cue-reactivity task, including the presentation of substance- or problematic behavior-related cues and at least one other class of cues (i.e., neutral or non-substance-related) for comparison. Acute challenge studies involving direct administration of substances of use were not included unless cues associated with the substance/object of use were explicitly presented as well. Cues also had to be ecologically valid; i.e., they needed to be associated with routine drug-taking behaviors and not be novel conditioned cues associated with the substance/object of use for the first time during the experiment. We excluded studies that did not provide details about the fMRI protocol, setting and tasks, outcomes of interest used in the analysis, and basic fMRI measures. There were no further exclusions, and both whole-brain and region of interest (ROI)-based fMRI studies were included.

**Participants: Every study required at least one human population or sub-population with more than one member, for which at least one of the following needed to be true:**

1. At least one circumscribed group of participants had a diagnosis of at least one SUD or BA, either manifest as active use or in remission; with the diagnosis made either before the study, as part of the study protocol during the investigation, or by the end of the study (i.e., with the diagnosis serving as an outcome measure).

2. At least one group of participants was included explicitly because they regularly consumed a potential object of addiction (substance or behavior) and/or had a risky pattern of consumption that might lead to addiction, and the study focused on their reactivity to cues of that substance or behavior.

3. At least one group of participants had been assigned a score for an addiction-related phenomenon (such as addiction or drug-use severity) with or without an explicit diagnosis of an SUD or BA, and the relationship of this score to important outcomes in the study had been investigated.

No restriction was placed on study participants based on demographic, ethnic, biological, or clinical factors (such as any co-occurring disorders).

**Language:** Only publications with their full text in English were included.

**Information source:** Existing research was identified and retrieved using PubMed. Relevant articles were identified using a comprehensive search strategy for all terms related to addiction, fMRI, and cue-reactivity, as detailed below.

**Search strategy:** Considering the subject of the review, a list of three sets of keywords was compiled (Supplementary Table 1). These terms were adapted for use in PubMed (exact search syntax and search results are outlined in Supplementary Table 2). The first set included synonyms of “functional magnetic resonance imaging”, the second included terms related to cue-reactivity, and the third included synonyms of “addiction” and various terms related to SUDs and BAs and addiction medicine. To help widen the search, no filters were used. The exclusion of systematic reviews and other non-original research and the application of other inclusion/exclusion criteria were handled manually. Given the large volume of relevant literature on PubMed, other search engines or grey literature were not used.

## Study records {-}

**Data management:** Literature search results were imported to Excel. Screening of articles for relevance was performed by reviewing the title and abstract sections of candidate texts, and full texts were obtained for studies that passed preliminary screening.

**Study selection:** Screening forms were developed for title/abstract and full-text assessment and studies were checked by two independent authors. The authors initially checked the eligibility of fifty randomly chosen studies under the supervision of the corresponding author (HE) as a calibration exercise to ensure eligibility criteria were applied consistently. After title and abstract screening, the two authors screened the full texts of papers that either met the eligibility criteria or had an uncertain status. Any papers with an uncertain eligibility status after full-text screening were then discussed with HE until a consensus on their inclusion was reached. Reasons for the exclusion of articles at the title and abstract or full-text screening stages were recorded, according to the PRISMA framework (Moher et al., 2015). Neither of the review authors was blind to the journal titles, study authors, or institutions.

**Data collection:** Data were filled into a spreadsheet. Consistency between the authors was honed through a calibration exercise in which all authors evaluated and discussed their ratings for 20 randomly chosen studies. AS, MZB and HE further refined the data extraction form to reduce inconsistency and ambiguity after the exercise. Data on study design features and basic methodological parameters were extracted first, and each article was reviewed independently by two authors in two separate spreadsheets, with inconsistencies resolved in discussions with MZB and AS with HE’s supervision.

**Data items:** We extracted publication details, publication country (where the first affiliation of the first study author is located or the affiliation of the majority of the authors in case country was not clear), publication year (based on PubMed’s indexing), the substance or behavior (main substance(s) and/or behavior(s) of interest in the study), main experimental task design type (whether cues were presented in blocked, event-related, or mixed forms), stimulus type (sensory modality of cues), combined tasks (whether cue-reactivity was paired with other tasks; and what tasks were used), task duration (seconds, excluding other paradigms that may have been implemented in the scanner), study sample characteristics (number of participants of each sex; number of participants with untreated or treated addictive disorders, drug-using individuals who did not meet substance use disorder criteria, individuals in long-term abstinence, and healthy non-using participants), intervention (if included, type of intervention), association with a future event (a non-fMRI variable measured at a later point in time based on fMRI results), number of fMRI sessions (times each participant was scanned), and interval between fMRI sessions (if participants were scanned more than once for a study, the average time interval between the scans). Yes/No ratings were used to classify whether the design of each FDCR study allowed for it to be potentially used to develop susceptibility, diagnostic, response, prognostic, predictive, or severity biomarkers for one or more SUDs/BAs. Yes/No ratings were also used to specify whether a study investigated relationships between FDCR-derived parameters and subjective craving, demographic variables, behavioral measures, biochemical assays, participant genetics, non-FDCR structural or functional neural markers, physiological parameters, or psychiatric assessments. For each study investigating use of FDCR as a biomarker type or assessing FDCR correlates, it was also rated as to whether significant test results were observed. However, we relied on simple reports of significance rather than analyzing reported effect sizes.

## Software {-}

The PubMed search engine from the National Library of Medicine’s online portal (https://www.ncbi.nlm.nih.gov/pubmed/) was used to conduct the search. Endnote X9 (The EndNote Team, 2013) was used for reference management. Google Sheets from Google’s Google Docs Editors suite was used to design tables for data extraction and sharing among authors. Data analyses and illustrations were conducted using R version 4.0.5 (R Core Team, 2013).

The protocol for this systematic review was developed throughout 2019 and was first registered on the Open Science Framework (OSF) website on May 18th, 2020.

**Link to the Live Database:**
[Here](https://docs.google.com/spreadsheets/d/1ZpGM57pZMhZZdD4IhxQw6sG_9uRJmukxCwrLPHZoMYU/edit?usp=drivesdk) you can find the link to the live database including all the studies and the extracted data.
